apiVersion: v1
kind: PersistentVolume
metadata:
    name: jupyterhub-pv
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/data" # Ensure this path exists on the host machine
