
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-demo-suc-deployment-20240515224441
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-demo-suc-20240515224441
  template:
    metadata:
      labels:
        app: test-demo-suc-20240515224441
    spec:
      containers:
      - name: mnist-data
        image: sarvagya23/mnist-fix:1.0
        command: ["python", "/app/mnist_classification_with_lenet_5_architecture.py"]
